modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="brooswit"
description='''Rope tools for NeoForge 1.21.1 (whip, grappling hooks, harpoon) built on Sable physics ropes. This build is a scaffold plus a rope spike.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[${sable_version},)"
    ordering="AFTER"
    side="BOTH"
